# Source all files from ~/.bash_includes
for f in ~/.bash_includes/*; do source $f; done

# Setup git-prompt
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1

# Prompt config
export PS1='\[\033[36m\]\u:\w\[\033[93m\]$(__git_ps1 " (%s)") \[\033[36m\]$ \[\033[0m\]'
